name: Bug Report
description: Report incorrect or unexpected behavior
title: "[Bug]: "
labels: ["type: bug"]
assignees: ["Craftinators"]

body:
  - type: markdown
    attributes:
      value: "Report incorrect or unexpected behavior of incandescence. If this doesn't look right, [choose a different type](https://github.com/Craftinators/incandescence/issues/new/choose)."
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with below code sample:
        1. Do whatever
        2. Observe behavior
        3. Read error logs
      validations:
        required: true
  - type: textarea
    id: codesample
    attributes:
      label: Code sample
      description: Include a reproducible, minimal code sample. This will be automatically formatted into code, so no need for backticks.
      render: typescript
      placeholder: |
        Your code sample should be:
        - Minimal: Use as little code as possible that still produces the same problem (and is understandable)
        - Complete: Provide all parts someone else needs to reproduce your problem
        - Reproducible: Test the code you're about to provide to make sure it reproduces the problem
  - type: input
    attributes:
      label: Package version
      description: "Which version of incandescence are you using? Run `npm list incandescence` in your project directory and paste the output."
      placeholder: "We don't support version 0.0.10 or earlier of incandescence"
    validations:
      required: true
  - type: input
    attributes:
      label: Node.js version
      description: "Which version of Node.js are you using? Run `node --version` in your project directory and paste the output."
      placeholder: "Node.js version 16.0+ is required for incandescence version 0.0.10+"
    validations:
      required: true
  - type: input
    attributes:
      label: Typescript version
      description: "If you are using TypeScript, please include its version. Run `npm list typescript` in your project directory and paste the output."
      placeholder: "Node.js version 16.0+ is required for incandescence version 0.0.10+"
